version: 2

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
           name: Setup environment
           command: |
             rustup component add rustfmt
             rustup update
      - run:
           name: Linter
           command: |
             rustfmt --version
             #cargo fmt --all -- --check
      - run:
          name: Build
          command: cargo build
      - run:
          name: Unit tests
          command: cargo test
